/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : IDL.Nat,
  'isBestSeller' : IDL.Bool,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getBestSellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCollections' : IDL.Func(
      [],
      [
        IDL.Record({
          'clothing' : IDL.Vec(Product),
          'homeAndKitchen' : IDL.Vec(Product),
          'bestSellers' : IDL.Vec(Product),
        }),
      ],
      ['query'],
    ),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : IDL.Nat,
    'isBestSeller' : IDL.Bool,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getBestSellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCollections' : IDL.Func(
        [],
        [
          IDL.Record({
            'clothing' : IDL.Vec(Product),
            'homeAndKitchen' : IDL.Vec(Product),
            'bestSellers' : IDL.Vec(Product),
          }),
        ],
        ['query'],
      ),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };