/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'rating' : bigint,
  'price' : bigint,
  'isBestSeller' : boolean,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getBestSellers' : ActorMethod<[], Array<Product>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCollections' : ActorMethod<
    [],
    {
      'clothing' : Array<Product>,
      'homeAndKitchen' : Array<Product>,
      'bestSellers' : Array<Product>,
    }
  >,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'updateCartQuantity' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];